// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8p_xpPPgvUuRi_BwhDviL6umeIjD15E',
    appId: '1:791787814827:web:0077c45d7eaf48c8df9cee',
    messagingSenderId: '791787814827',
    projectId: 'gpsapp-413714',
    authDomain: 'gpsapp-413714.firebaseapp.com',
    databaseURL: 'https://gpsapp-413714-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpsapp-413714.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFU-rBRWteNKGOuwwVXJwxS6HZI1QepJU',
    appId: '1:791787814827:android:9c4be49d22d20e95df9cee',
    messagingSenderId: '791787814827',
    projectId: 'gpsapp-413714',
    databaseURL: 'https://gpsapp-413714-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpsapp-413714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm4mWsdeqak4If8ZYGcJrPVOuMre7MvEE',
    appId: '1:791787814827:ios:77dc4f96c425f60cdf9cee',
    messagingSenderId: '791787814827',
    projectId: 'gpsapp-413714',
    databaseURL: 'https://gpsapp-413714-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpsapp-413714.appspot.com',
    iosBundleId: 'com.example.gpsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm4mWsdeqak4If8ZYGcJrPVOuMre7MvEE',
    appId: '1:791787814827:ios:9236ceb999a1d959df9cee',
    messagingSenderId: '791787814827',
    projectId: 'gpsapp-413714',
    databaseURL: 'https://gpsapp-413714-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpsapp-413714.appspot.com',
    iosBundleId: 'com.example.gpsapp.RunnerTests',
  );
}
